name: Supabase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://supabase.com/cli/install.sh | sh

      - name: Link Supabase Project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Push Supabase Migrations
        run: |
          supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Deploy Supabase Functions (if any)
        run: |
          supabase functions deploy --no-verify-jwt || true
